sudo: required

services:
  - docker

before_script:
  - docker-compose -v

script:
  - docker-compose build tests-with-report
  - >
    docker-compose run
    --rm
    -e ENV_GMAIL_EXTRACTOR_APP_KEY=$ENV_GMAIL_EXTRACTOR_APP_KEY
    -e ENV_GMAIL_EXTRACTOR_APP_SECRET=$ENV_GMAIL_EXTRACTOR_APP_SECRET
    -e ENV_GMAIL_EXTRACTOR_ACCESS_TOKEN_JSON=$ENV_GMAIL_EXTRACTOR_ACCESS_TOKEN_JSON
    -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    tests-with-report

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
