version: "2"

services:

  app:
    build: .
    image: keboola/gmail-extractor
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    command: bash

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: ./tests.sh

  tests-with-report:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - ./.git:/code/.git
    command: >
             sh -c '
             ./tests.sh
             && ./vendor/bin/test-reporter
             '
